
export const countries = [
  { name: 'Afghanistan', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'] },
  { name: 'Albania', cities: ['Tirana', 'Durres', 'Vlore', 'Shkoder'] },
  { name: 'Algeria', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba'] },
  { name: 'Andorra', cities: ['Andorra la Vella'] },
  { name: 'Argentina', cities: ['Buenos Aires', 'Cordoba', 'Rosario'] },
  { name: 'Australia', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'] },
  { name: 'Austria', cities: ['Vienna', 'Graz', 'Linz'] },
  { name: 'Azerbaijan', cities: ['Baku', 'Ganja', 'Sumqayit'] },
  { name: 'Bahrain', cities: ['Manama', 'Riffa'] },
  { name: 'Bangladesh', cities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi'] },
  { name: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent'] },
  { name: 'Bosnia and Herzegovina', cities: ['Sarajevo', 'Banja Luka', 'Tuzla'] },
  { name: 'Brazil', cities: ['Sao Paulo', 'Rio de Janeiro', 'Brasilia'] },
  { name: 'Brunei', cities: ['Bandar Seri Begawan'] },
  { name: 'Bulgaria', cities: ['Sofia', 'Plovdiv', 'Varna'] },
  { name: 'Burkina Faso', cities: ['Ouagadougou'] },
  { name: 'Cambodia', cities: ['Phnom Penh'] },
  { name: 'Canada', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Ottawa'] },
  { name: 'Chad', cities: ['N\'Djamena'] },
  { name: 'Chile', cities: ['Santiago'] },
  { name: 'China', cities: ['Beijing', 'Shanghai', 'Guangzhou', 'Urumqi'] },
  { name: 'Colombia', cities: ['Bogota', 'Medellin'] },
  { name: 'Comoros', cities: ['Moroni'] },
  { name: 'Croatia', cities: ['Zagreb'] },
  { name: 'Cyprus', cities: ['Nicosia'] },
  { name: 'Czech Republic', cities: ['Prague'] },
  { name: 'Denmark', cities: ['Copenhagen'] },
  { name: 'Djibouti', cities: ['Djibouti'] },
  { name: 'Egypt', cities: ['Cairo', 'Alexandria', 'Giza', 'Luxor'] },
  { name: 'Estonia', cities: ['Tallinn'] },
  { name: 'Ethiopia', cities: ['Addis Ababa'] },
  { name: 'Finland', cities: ['Helsinki'] },
  { name: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse'] },
  { name: 'Georgia', cities: ['Tbilisi'] },
  { name: 'Germany', cities: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt'] },
  { name: 'Ghana', cities: ['Accra'] },
  { name: 'Greece', cities: ['Athens', 'Thessaloniki'] },
  { name: 'Hungary', cities: ['Budapest'] },
  { name: 'Iceland', cities: ['Reykjavik'] },
  { name: 'India', cities: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Kolkata'] },
  { name: 'Indonesia', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan'] },
  { name: 'Iran', cities: ['Tehran', 'Mashhad', 'Isfahan', 'Shiraz'] },
  { name: 'Iraq', cities: ['Baghdad', 'Basra', 'Mosul', 'Erbil'] },
  { name: 'Ireland', cities: ['Dublin'] },
  { name: 'Italy', cities: ['Rome', 'Milan', 'Naples', 'Turin'] },
  { name: 'Japan', cities: ['Tokyo', 'Osaka', 'Nagoya'] },
  { name: 'Jordan', cities: ['Amman', 'Zarqa', 'Irbid'] },
  { name: 'Kazakhstan', cities: ['Almaty', 'Nur-Sultan', 'Shymkent'] },
  { name: 'Kenya', cities: ['Nairobi', 'Mombasa'] },
  { name: 'Kosovo', cities: ['Pristina'] },
  { name: 'Kuwait', cities: ['Kuwait City'] },
  { name: 'Kyrgyzstan', cities: ['Bishkek'] },
  { name: 'Lebanon', cities: ['Beirut', 'Tripoli'] },
  { name: 'Libya', cities: ['Tripoli', 'Benghazi'] },
  { name: 'Malaysia', cities: ['Kuala Lumpur', 'George Town', 'Johor Bahru'] },
  { name: 'Maldives', cities: ['Male'] },
  { name: 'Mali', cities: ['Bamako'] },
  { name: 'Mauritania', cities: ['Nouakchott'] },
  { name: 'Mexico', cities: ['Mexico City', 'Guadalajara'] },
  { name: 'Montenegro', cities: ['Podgorica'] },
  { name: 'Morocco', cities: ['Rabat', 'Casablanca', 'Fes', 'Marrakesh'] },
  { name: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague'] },
  { name: 'New Zealand', cities: ['Auckland', 'Wellington'] },
  { name: 'Niger', cities: ['Niamey'] },
  { name: 'Nigeria', cities: ['Lagos', 'Kano', 'Abuja'] },
  { name: 'North Macedonia', cities: ['Skopje'] },
  { name: 'Norway', cities: ['Oslo'] },
  { name: 'Oman', cities: ['Muscat', 'Salalah'] },
  { name: 'Pakistan', cities: ['Karachi', 'Lahore', 'Islamabad', 'Peshawar'] },
  { name: 'Palestine', cities: ['Jerusalem', 'Gaza', 'Ramallah'] },
  { name: 'Philippines', cities: ['Manila'] },
  { name: 'Poland', cities: ['Warsaw'] },
  { name: 'Portugal', cities: ['Lisbon'] },
  { name: 'Qatar', cities: ['Doha'] },
  { name: 'Romania', cities: ['Bucharest'] },
  { name: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Kazan', 'Grozny'] },
  { name: 'Rwanda', cities: ['Kigali'] },
  { name: 'Saudi Arabia', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam'] },
  { name: 'Senegal', cities: ['Dakar'] },
  { name: 'Serbia', cities: ['Belgrade'] },
  { name: 'Singapore', cities: ['Singapore'] },
  { name: 'Somalia', cities: ['Mogadishu'] },
  { name: 'South Africa', cities: ['Johannesburg', 'Cape Town', 'Durban'] },
  { name: 'South Korea', cities: ['Seoul'] },
  { name: 'Spain', cities: ['Madrid', 'Barcelona', 'Cordoba'] },
  { name: 'Sri Lanka', cities: ['Colombo'] },
  { name: 'Sudan', cities: ['Khartoum'] },
  { name: 'Sweden', cities: ['Stockholm', 'Malmo'] },
  { name: 'Switzerland', cities: ['Zurich', 'Geneva'] },
  { name: 'Syria', cities: ['Damascus', 'Aleppo', 'Homs'] },
  { name: 'Taiwan', cities: ['Taipei'] },
  { name: 'Tajikistan', cities: ['Dushanbe'] },
  { name: 'Tanzania', cities: ['Dar es Salaam', 'Dodoma'] },
  { name: 'Thailand', cities: ['Bangkok'] },
  { name: 'Tunisia', cities: ['Tunis', 'Sfax'] },
  { name: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Konya'] },
  { name: 'Turkmenistan', cities: ['Ashgabat'] },
  { name: 'Uganda', cities: ['Kampala'] },
  { name: 'Ukraine', cities: ['Kyiv'] },
  { name: 'United Arab Emirates', cities: ['Dubai', 'Abu Dhabi', 'Sharjah'] },
  { name: 'United Kingdom', cities: ['London', 'Birmingham', 'Manchester', 'Glasgow'] },
  { name: 'United States', cities: ['New York', 'Dearborn', 'Los Angeles', 'Chicago', 'Houston'] },
  { name: 'Uzbekistan', cities: ['Tashkent', 'Samarkand', 'Bukhara'] },
  { name: 'Yemen', cities: ['Sana\'a', 'Aden'] },
  { name: 'Zambia', cities: ['Lusaka'] },
  { name: 'Zimbabwe', cities: ['Harare'] },
];
